### ISSUE TITLE
Wrong Instruction on AZ400_M12_Feature_Flag_Management_with_LaunchDarkly_and_Azure_DevOps.

### ISSUE THREAD

**Issue by meatloaf111** [MicrosoftLearning/AZ-400JA-Designing-and-Implementing-Microsoft-DevOps-solutions#6]
# Module: 12
#### Step: 16

Description of issue
The step says (in Japanese) that you should change the 'HomeController.cs code snippet' but the linked source code suggests that AccountController.cs

**Comment by LuongNguyen0906** [comment]
Hi,

we are investigating issue. will keep you posted. 

Thanks.

**Comment by LuongNguyen0906** [comment]
this will be fixed in the release after June 17th.
